---
- name: Deploy the application
  hosts: [your_instance_id]
  become: yes

  tasks:
  - name: Pull the Docker image
    docker_image:
      name: ${ECR_REGISTRY}/${APP_REPO_NAME}
      source: pull

  - name: Create a Docker container
    docker_container:
      name: your_app_name
      image: ${ECR_REGISTRY}/${APP_REPO_NAME}
      ports:
        - "80:80"
      restart: always
